### PR TITLE
Test cases for Calendar

### LINKED ISSUE #74: Calendar event start date is incorrect
* Calendar Event should show the event with the start date included. But it is excluding it.
image
image

### PR DESCRIPTION
**Pull request by prateekshourya29**
# PR Details

## Description

Add test for calendar component

## Related Issue

#39 
Also fixes #74 

## Motivation and Context

* For coverage.

## How Has This Been Tested

Tested using jest with the help of react testing library.

## Types of changes

- [ ] Docs change / refactoring / dependency upgrade
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

File: src/components/Calendar/Calendar.tsx [hunk 1]
```diff
@@ -130,6 +127,8 @@ export const Calendar: React.FC<CalendarProps> = (props) => {
     });
   };
 
+  const css = style;
+
   const getdateArray = () => {
```
Comment (anitnilay20) [inline src/components/Calendar/Calendar.tsx:132]:
```suggestion
  const getDateArray = () => {
```

File: __tests__/components/Calendar/Calendar.spec.tsx [hunk 2]
```diff
@@ -0,0 +1,319 @@
...
+  });
+
+  it('Should check weeks of calendar', () => {
+    render(<Calendar />);
+
+    const weeks = document.querySelectorAll('.sha-el-row')[1].querySelectorAll('.sha-el-col');
+    expect(weeks.length).toBe(7);
+  });
+
+  it('Should render correct date postion', () => {
```
Comment (anitnilay20) [inline __tests__/components/Calendar/Calendar.spec.tsx:99]:
```suggestion
  it('Should render correct date week name', () => {
```

File: __tests__/components/Calendar/Calendar.spec.tsx [hunk 3]
```diff
@@ -0,0 +1,319 @@
...
+
+    act(() => {
+      fireEvent.click(datesArray[9]);
+    });
+    expect(datesArray[9]).toHaveStyle(`
+      color: #555555;
+    `);
+  });
+
+  it('Should change date when month changes', () => {
```
Comment (anitnilay20) [inline __tests__/components/Calendar/Calendar.spec.tsx:136]:
```suggestion
  it('Should re-render on month changes', () => {
```

File: __tests__/components/Calendar/Calendar.spec.tsx [hunk 4]
```diff
@@ -0,0 +1,319 @@
...
+    });
+    const monthArray = document.querySelector('ul').querySelectorAll('li');
+    act(() => {
+      fireEvent.click(monthArray[11]);
+    });
+
+    expect(datesArray[6].querySelector('button').innerHTML).toBe('<span>1</span>');
+  });
+
+  it('Should change date when year changes', () => {
```
Comment (anitnilay20) [inline __tests__/components/Calendar/Calendar.spec.tsx:154]:
```suggestion
  it('Should re-render when year changes', () => {
```

File: __tests__/components/Calendar/Calendar.spec.tsx [hunk 5]
```diff
@@ -0,0 +1,319 @@
...
+    });
+    const yearArray = document.querySelector('ul').querySelectorAll('li');
+    act(() => {
+      fireEvent.click(yearArray[2025 - 1980]);
+    });
+
+    expect(datesArray[2].querySelector('button').innerHTML).toBe('<span>1</span>');
+  });
+
+  it('Should check date click', () => {
```
Comment (anitnilay20) [inline __tests__/components/Calendar/Calendar.spec.tsx:172]: Should be a part of `Should change date background on click`.

File: __tests__/components/Calendar/Calendar.spec.tsx [hunk 6]
```diff
@@ -0,0 +1,319 @@
...
+    for (let i = 3; i < 31; i += 7) {
+      expect(datesArray[i].querySelector('button')).toHaveStyle(`
+        background: transparent;
+        cursor: not-allowed;
+        color: rgba(0, 0, 0, 0.20);
+      `);
+    }
+  });
+
+  it('Should disable click on disabled dates', () => {
```
Comment (anitnilay20) [inline __tests__/components/Calendar/Calendar.spec.tsx:219]: Can be a part of `Should render a calendar with disabled dates`.

**Review by anitnilay20 — CHANGES_REQUESTED** [review]

**Review by anitnilay20 — APPROVED** [review]
